#!/bin/bash



pushd /Volumes/qubuntuFileServer/cmerdc/lightningPipe/system/management/devEnvironment/parameterFiles/studentPlansSource/current > /dev/null;

combinedSetsDir="zCombinedComponentsTmp"

destFileDirPath="$testLinkDir/testDataDest";
schoolSpecsDir="buildSchoolSpecs";
componentsDir="buildComponents";


shopt -s extglob

sqlAuth="qubuntuMysqlAuth.json";
destType="file"

if [[ "-e" == "$1" ]]; then
sqlAuth="elearningMsyqlAuth.json"
fi
if [[ "-e" == "$2" ]]; then
sqlAuth="elearningMsyqlAuth.json"
fi

if [[ "-f" == "$1" ]]; then
destType="file"
fi
if [[ "-f" == "$2" ]]; then
destType="file"
fi

schoolNameList=(\
'Albany' \
'Badger' \
'Barnesville' \
'Browns-Valley' \
'Clinton-Graceville' \
'Hancock' \
'Hawley' \
'Morris' \
'Paynesville' \
'Ulen-Hitterdahl' \
'Upsala' \
'WCE' \
'Wheaton' \
)

echo -e "\n\n"`date` " Starting Run ============================";


for schoolName in ${schoolNameList[*]}; do
templateReplace.js buildTemplates/plansBase.txt assembledParameterSets/$schoolName.json -f  \
 --databaseName="zzStudentPlans" \
 --destFileDirPath="$destFileDirPath" \
 --destType="$destType" \
 --overwrite="(function(item) { if (item.overwriteFlag) { return '\"overwrite\":\"all\"'; } else { return '\"overwrite\":[]' } })" \
 --sqlAuth=$sqlAuth \
 --urlList="urlLists/$schoolName.js" \
 --schoolName="$schoolName"

done


if [[ "file" == "$destType" ]]; then

if [[ "-e" == "$1" ]]; then
tmp="(ignored mysqlAuth spec)"
fi
if [[ "-e" == "$2" ]]; then
tmp="(ignored mysqlAuth spec)"
fi

echo -e "Created for file output to $destFileDirPath\n$tmp"
else
echo -e "Created for mysql output to $sqlAuth"
fi

echo -e `date` " Ending Run ============================\n\n";

popd > /dev/null;