[
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/001/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/001/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/001/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},

{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/002/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/002/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/002/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},

{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/020/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/020/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/020/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Paynesville/Students.txt", "path":"Data", "switches":{"header":false, "append":true}}
]