$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/030/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/030/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/030/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/035/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/035/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/035/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/050/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/050/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/050/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/060/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/060/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/060/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/099/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/099/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/099/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Albany/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/001/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/001/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/001/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/003/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/003/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/003/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/006/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/006/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Clinton-Graceville/schools/006/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Clinton-Graceville/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Hancock/schools/020/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Hancock/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Hancock/schools/020/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Hancock/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Hancock/schools/020/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Hancock/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Morris/schools/010/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Morris/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Morris/schools/010/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Morris/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Morris/schools/010/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Morris/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Morris/schools/030/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Morris/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Morris/schools/030/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Morris/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Morris/schools/030/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Morris/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/001/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/001/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/001/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/002/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/002/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/002/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/020/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/020/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Paynesville/schools/020/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Paynesville/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/020/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/020/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/020/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/023/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/023/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/023/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/024/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/024/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/024/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/025/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/025/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/WCE/schools/025/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/WCE/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Wheaton/schools/001/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Wheaton/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Wheaton/schools/001/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Wheaton/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Wheaton/schools/001/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Wheaton/Students.txt -a

$cloverleaf http://localhost:8081/uff/1.0/districts/Wheaton/schools/002/segments/Guardian#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Wheaton/Guardians.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Wheaton/schools/002/segments/Schedule#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Wheaton/Schedules.txt -a
$cloverleaf http://localhost:8081/uff/1.0/districts/Wheaton/schools/002/segments/Student_Enrolled#Data?sendFlatSpecs=true $cloverleaf http://localhost:8081/uff/1.0/districts/Albany/schools/010/segments/Guardian#Data?sendFlatSpecs=true /Volumes/qubuntuFileServer/cmerdc/lightningPipe/testResults/Albany/Guardians.txt -a/Wheaton/Students.txt -a
