#!/bin/sh

mv 0745 Albany
mv 2888 Clinton-GraceVille
mv 0768 Hancock
mv 2769 Morris
mv 0741 Paynesville
mv 6026 WCE
mv 0803 Wheaton

mv 0146 Barnesville
mv 0801 Browns-Valley
mv 0150 Hawley
mv 0914 Ulen-Hitterdahl
mv 0487 Upsala