#!/bin/sh

echo "don't forget clNumbersToName";

cd $clTestDestDir;
export studentTmp="Students.txt";

# #Albany ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Albany/schools/0745_010/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Albany/schools/0745_030/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Albany/schools/0745_035/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Albany/schools/0745_050/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Albany/schools/0745_060/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Albany/schools/0745_099/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a


# #Clinton-Graceville ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Clinton-GraceVille/schools/2888_001/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Clinton-GraceVille/schools/2888_003/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Clinton-GraceVille/schools/2888_006/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a

# #Hancock ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Hancock/schools/0768_010/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h

# #Morris ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Morris/schools/2769_010/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Morris/schools/2769_030/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a

# #Paynesville ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Paynesville/schools/0741_001/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Paynesville/schools/0741_002/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Paynesville/schools/0741_020/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a

# #WCE ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/WCE/schools/6026_020/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/WCE/schools/6026_024/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/WCE/schools/6026_025/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a

# #Wheaton ===============================================
# rm $studentTmp;
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Wheaton/schools/0803_001/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h
# $cloverleaf \
# http://localhost:8081/uff/1.0/districts/Wheaton/schools/0803_002/segments/Student_Enrolled#Data?sendFlatSpecs=true \
# $studentTmp \
# -h -a
