#!/bin/sh

echo "--school"; node ../ebControl.js --school --pingOnly dataFiles/eb/schoolSetup/school.eb;

echo "--gradeLevel"; node ../ebControl.js --gradeLevel --pingOnly dataFiles/eb/schoolSetup/gradeLevel.eb;

echo "--gradeLevelSchool"; node ../ebControl.js --gradeLevelSchool --pingOnly dataFiles/eb/schoolSetup/gradeLevelSchool.eb;

echo "--term"; node ../ebControl.js --term --pingOnly -- dataFiles/eb/schoolSetup/term.eb;

echo "--termSchool"; node ../ebControl.js --termSchool --pingOnly -- dataFiles/eb/schoolSetup/termSchool.eb;

echo "--schoolSetCurrentTerm"; node ../ebControl.js --schoolSetCurrentTerm --pingOnly -- dataFiles/eb/schoolSetup/school.eb;

echo "--student"; node ../ebControl.js --student --pingOnly -- dataFiles/eb/peopleSetup/student.eb;

echo "--teacher"; node ../ebControl.js --teacher --pingOnly -- dataFiles/eb/peopleSetup/teacher.eb;

echo "--homeroom"; node ../ebControl.js --homeroom --skipFirstLine --pingOnly -- dataFiles/eb/peopleSetup/homeroom.eb;

echo "--assignStudent"; node ../ebControl.js --assignStudent --pingOnly dataFiles/eb/assignStudent.eb;

echo "--assignTeacher"; node ../ebControl.js --assignTeacher --pingOnly dataFiles/eb/assignTeacher.eb;

echo "school"; node ../ebControl.js --school --pingOnly  dataFiles/eb/schoolSetup/school.eb
echo "gradeLevel"; node ../ebControl.js --gradeLevel --pingOnly  dataFiles/eb/schoolSetup/gradeLevel.eb
echo "gradeLevelSchool"; node ../ebControl.js --gradeLevelSchool --pingOnly  dataFiles/eb/schoolSetup/gradeLevelSchool.eb
echo "term"; node ../ebControl.js --term --pingOnly  -- dataFiles/eb/schoolSetup/term.eb
echo "termSchool"; node ../ebControl.js --termSchool --pingOnly  -- dataFiles/eb/schoolSetup/termSchool.eb
echo "schoolSetCurrentTerm"; node ../ebControl.js --schoolSetCurrentTerm --pingOnly  -- dataFiles/eb/schoolSetup/school.eb


echo "objective"; node ../ebControl.js --objective --pingOnly dataFiles/uff/objectiveSetup/objectives.eb
echo "assignGradeLevel"; node ../ebControl.js --assignGradeLevel --pingOnly dataFiles/uff/objectiveSetup/gradeLevelAssignments.eb
echo "assignTerm"; node ../ebControl.js --assignTerm --pingOnly dataFiles/uff/objectiveSetup/termAssignments.eb
echo "assignSpecialty"; node ../ebControl.js --assignSpecialty --pingOnly dataFiles/uff/objectiveSetup/specialtyAssignments.eb


echo "specialty"; node ../ebControl.js --specialty --pingOnly dataFiles/eb/attributeSetup/specialties.eb
echo "markScale"; node ../ebControl.js --markScale --pingOnly dataFiles/eb/objectiveSetup/markScales.eb