#!/bin/sh

mv Albany 0745
mv Clinton-GraceVille 2888
mv Hancock 0768
mv Morris 2769
mv Paynesville 0741
mv WCE 6026
mv Wheaton 0803

mv Barnesville 0146
mv Browns-Valley 0801
mv Hawley 0150
mv Ulen-Hitterdahl 0914
mv Upsala 0487