{"query":"create table Enrollments as select distinct ss.staffUniqueIdentifier as courseId, ss.staffUniqueIdentifier as personId, 'editingteacher' as role, c.courseAbbreviation || '_' || s.schoolYearBegin || '_' || s.schoolYearEnd || '_' || s.termAbbreviation as 'classGroup' from Course as c left join Section_Staff as ss on ss.courseNumber=c.courseNumber left join Section as s on s.sectionNumber=ss.sectionNumber where trim(personId) <> '' and trim(personId) <> '' and trim(classGroup) <> '' and trim(courseId) <> '' and ss.PrimaryInstructorFlag='Y' "},

{"query":"insert into Enrollments select c.courseNumber || '_' || ss.staffUniqueIdentifier as personId, sst.studentUniqueIdentifier as userId, 'student' as role, s.termAbbreviation || '_' || s.beginningPeriodNumber as 'classGroup' from Course as c left join Section_Staff as ss on ss.courseNumber=c.courseNumber left join Section as s on s.sectionNumber=ss.sectionNumber left join Section_Student as sst on sst.sectionNumber=s.sectionNumber where trim(personId) <> '' and trim(userId) <> '' and trim(classGroup) <> ''"},

{"query":"create table NewCourses as select ss.firstName || '_' || ss.lastName as fullName, ss.lastName || '_' || ss.staffUniqueIdentifier as shortName, ss.staffUniqueIdentifier as courseId, '' as template, ss.schoolCode as categoryPath, ss.schoolCode as categoryId, ss.schoolCode as categoryName, ss.schoolCode as categoryDescription from Section_Staff as ss where trim(fullName) <> '' and trim(shortName) <> '' and trim(courseId) <> ''"},

{"query":"create table Users as select j.staffUniqueIdentifier as personId, j.staffUniqueIdentifier as userName, 'Te$tUs3r' as password, j.firstName as firstName, j.lastName as lastName, j.lastName || '_' || j.firstName || '@emailaddress.edu' as email, '' as city, '' as street, '' as phone1, '' as phone2, '' as grade, '' as gradYear, j.schoolCode as schoolCode, 'STAFF' as department, 'US' as country from JMC_User as j where trim(personId) <> '' and trim(userName) <> '' and trim(password) <> '' and trim(firstName) <> '' and trim(lastName) <> '' and trim(email) <> '' "},

{"query":"insert into Users select sb.studentUniqueIdentifier as personId, sb.lastName || '_' || sb.firstName || '_' || substr(sb.studentUniqueIdentifier, 0, 4) as userName, sb.lastName as password, sb.firstName as firstName, sb.lastName as lastName, sb.lastName || '_' || sb.firstName || '@emailadr.edu' as email, ac.city as city, ac.address1 as street, ac.contactPhone1 as phone1, ac.contactPhone2 as phone2, sb.gradeLevelLevel as grade, sb.graduationYear as gradYear, sb.schoolCode as schoolCode, 'STUDENT' as department, 'US' as country from Student_Base as sb left join Address_Contact as ac on ac.studentUniqueIdentifier=sb.studentUniqueIdentifier where trim(personId) <> '' and trim(userName) <> '' and trim(password) <> '' and trim(firstName) <> '' and trim(lastName) <> '' and trim(email) <> '' "}
