[
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/010/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/010/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/010/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/020/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/020/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/020/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/999/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/999/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Browns%20Valley/schools/999/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Browns-Valley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}}
]