[
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/010/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/010/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/010/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/011/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/011/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/011/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/020/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/020/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/020/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/099/segments/Guardian?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/099/segments/Schedule?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://lightningpipe.org:8001/uff/1.0/districts/Hawley/schools/099/segments/Student_Enrolled?sendFlatSpecs=true","destination":"/home/lightningpipe/mountPoint/destDirProd/Hawley/Students.txt", "path":"Data", "switches":{"header":false, "append":true}}
]
