[
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/001/segments/Guardian/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/001/segments/Schedule/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/001/segments/Student_Enrolled/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},

{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/002/segments/Guardian/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/002/segments/Schedule/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/002/segments/Student_Enrolled/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Students.txt", "path":"Data", "switches":{"header":false, "append":true}},

{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/020/segments/Guardian/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Guardians.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/020/segments/Schedule/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Schedules.txt", "path":"Data", "switches":{"header":false, "append":true}},
{"source":"http://demo.api.lightningpipe.org/uff/1.0/districts/Paynesville/schools/020/segments/Student_Enrolled/segments/Guardian","destination":"/home/lightningpipe/mountPoint/destDirDemo/Paynesville/Students.txt", "path":"Data", "switches":{"header":false, "append":true}}
]