#!/bin/sh
echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/albany\n';
curl -s http://localhost:8000/uff/1.0/districts/albany?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/099/segments\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/099/segments?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/099/segmentss\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/099/segmentss?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/099\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/099?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/albany\n';
curl -s http://localhost:8000/uff/1.0/districts/albany?test > /dev/null;

echo 'curl -s http://localhost:8000/uff/1.0/districts/\n';
curl -s http://localhost:8000/uff/1.0/districts/?test > /dev/null;




echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Address_Contact\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Address_Contact?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Course\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Course?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/User_Base\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/User_Base?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Lookups\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Lookups?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Section\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Section?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Section_Staff\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Section_Staff?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Section_Student\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Section_Student?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Attendance\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Attendance?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Base\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Base?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Discipline\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Discipline?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Enrollment\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Enrollment?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_GPA\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_GPA?test > /dev/null;


echo 'curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Grades\n';
curl -s http://localhost:8000/uff/1.0/districts/albany/schools/010/segments/Student_Grades?test > /dev/null;
