#!/bin/sh
echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2 > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/albany\n';
curl -s http://localhost:8081/uff/1.0/districts/albany > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/099/segments\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/099/segments > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/099/segmentss\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/099/segmentss > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/099\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/099 > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/albany\n';
curl -s http://localhost:8081/uff/1.0/districts/albany > /dev/null;

echo 'curl -s http://localhost:8081/uff/1.0/districts/\n';
curl -s http://localhost:8081/uff/1.0/districts/ > /dev/null;




echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Address_Contact\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Address_Contact > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Course\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Course > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/User_Base\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/User_Base > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Lookups\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Lookups > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Section\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Section > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Section_Staff\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Section_Staff > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Section_Student\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Section_Student > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/StudentBaseTest2 > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Attendance\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Attendance > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Base\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Base > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Discipline\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Discipline > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Enrollment\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Enrollment > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_GPA\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_GPA > /dev/null;


echo 'curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Grades\n';
curl -s http://localhost:8081/uff/1.0/districts/albany/schools/010/segments/Student_Grades > /dev/null;
